language: node_js
node_js:
- node

before_script:
- mkdir travis-phantomjs
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
- export PATH=$PWD/travis-phantomjs:$PATH

notification :J
  slack:
    secure: EyAkTreTNh6NWdKKn6vXgqufWope7amdVMc2wATmI1IyUZsm12MBTDJ22Ftf1eMmV149xLwYycHRx9Yh6jGjccxIIo+S1rqN7xCkix3yADntV8DFFIAPFs74EtM4YEvp5lQtm2wrk3F+7lu2PPSSkouUEPFS/yeZrMSuvoSo7O0WFIhSW978vN1pe6hDdLej8hNPH5V5vsgT0v8wCz3fY95ulScr1z8cFHZlaxlZLaLx9T9wv7cgRG2BEimG+rkXS94isRH8P9NZhWuvVPhxvycSzzfosUFzEq2ONU0gRaauaPz2TRR1FjOKfXw84A3KVaMEJygkrtHTP72SnozSCHwPv4g1TsLlS+BR0N+NgxuOVr30pT6hj7bPqWCTskO9ub3m3aEtIwwb5NmK9Biqcqzm4x/yTlsjDhgWkGiLHxoGKNqZQ1ca7SwYYGSVYCjDdCLQtOBIEgnmEf/sYtCygeVNfZ9/DE6p5KvfbkBPLj/Nti5xfm9NbVKxNubGHYs7iJT1pOCXNq4Gsm0+hZVjyJzxZzZYnsoTnz+qq/XCiDkiqqhxzwzXGulvgJCarngC8CW9b6JTi/kUVe/yq3zT2CMYS3aXKFQ+yLhdTxKdYA22xzGgLWyhAajzuWTD5FBGU5Dl8eUpwhkrDoH/HCubJpNQw12eYBopQDsjMLdaNjs=
