language: java
jdk:
  - oraclejdk8
  - oraclejdk7

branches:
  only:
  - development
  - selenium_experimental

before_install:
  - sudo apt-get -y install nodejs
  - ./selenium_setup.sh

notifications:
  slack: 371team3:TB8PmfcQFNgUvytSnno8zVUZ