language: java
jdk:
  - oraclejdk8
  - oraclejdk7

branches:
  only:
  - development
  - selenium

sudo: true

notifications:
  slack: 
    rooms:
        - '371team3:R6TEyOqBzUzFY13wyDs3OXJZ'
    on_success: always
    on_failure: always

before_install:
  - sudo apt-get -y install nodejs
  - bash selenium_setup.sh
