language: java
jdk:
  - oraclejdk8
  - oraclejdk7

branches:
  only:
  - development
  - selenium_experimental

notifications:
  slack: 371team3:TB8PmfcQFNgUvytSnno8zVUZ

before_install:
  - ./selenium_setup.sh
