language: java
jdk:
  - oraclejdk8

branches:
  only:
  - development
  - selenium

sudo: true

notifications:
  slack:
    rooms:
        - '371team3:R6TEyOqBzUzFY13wyDs3OXJZ'
    on_success: always
    on_failure: always

before_install:
  - sudo apt-get -y install nodejs
  - sudo apt-get install npm
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - bash selenium_setup.sh


before_script:
  - sudo npm install -g grunt


script:
  - grunt test --verbose --force
  - mvn test -f ./src/Maven/pom.xml
