
var __cov_o_ZhbKAUy_F7iJMPdQoW0w = (Function('return this'))();
if (!__cov_o_ZhbKAUy_F7iJMPdQoW0w.__coverage__) { __cov_o_ZhbKAUy_F7iJMPdQoW0w.__coverage__ = {}; }
__cov_o_ZhbKAUy_F7iJMPdQoW0w = __cov_o_ZhbKAUy_F7iJMPdQoW0w.__coverage__;
if (!(__cov_o_ZhbKAUy_F7iJMPdQoW0w['/Users/cooldued59/Git Projects/CMPT 371 QM-Lab/src/Main/checkcollaballowed.js'])) {
   __cov_o_ZhbKAUy_F7iJMPdQoW0w['/Users/cooldued59/Git Projects/CMPT 371 QM-Lab/src/Main/checkcollaballowed.js'] = {"path":"/Users/cooldued59/Git Projects/CMPT 371 QM-Lab/src/Main/checkcollaballowed.js","s":{"1":1,"2":0,"3":1,"4":0,"5":1,"6":0},"b":{},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"allowCollabRecording","line":18,"loc":{"start":{"line":18,"column":0},"end":{"line":18,"column":32}}},"2":{"name":"stopCollabRecording","line":29,"loc":{"start":{"line":29,"column":0},"end":{"line":29,"column":31}}},"3":{"name":"isCollabRecordingAllowed","line":38,"loc":{"start":{"line":38,"column":0},"end":{"line":38,"column":36}}}},"statementMap":{"1":{"start":{"line":18,"column":0},"end":{"line":20,"column":1}},"2":{"start":{"line":19,"column":1},"end":{"line":19,"column":37}},"3":{"start":{"line":29,"column":0},"end":{"line":31,"column":1}},"4":{"start":{"line":30,"column":1},"end":{"line":30,"column":36}},"5":{"start":{"line":38,"column":0},"end":{"line":40,"column":1}},"6":{"start":{"line":39,"column":1},"end":{"line":39,"column":37}}},"branchMap":{}};
}
__cov_o_ZhbKAUy_F7iJMPdQoW0w = __cov_o_ZhbKAUy_F7iJMPdQoW0w['/Users/cooldued59/Git Projects/CMPT 371 QM-Lab/src/Main/checkcollaballowed.js'];
function allowCollabRecording(){__cov_o_ZhbKAUy_F7iJMPdQoW0w.f['1']++;__cov_o_ZhbKAUy_F7iJMPdQoW0w.s['2']++;collaborativeChangeReceived=false;}function stopCollabRecording(){__cov_o_ZhbKAUy_F7iJMPdQoW0w.f['2']++;__cov_o_ZhbKAUy_F7iJMPdQoW0w.s['4']++;collaborativeChangeReceived=true;}function isCollabRecordingAllowed(){__cov_o_ZhbKAUy_F7iJMPdQoW0w.f['3']++;__cov_o_ZhbKAUy_F7iJMPdQoW0w.s['6']++;return!collaborativeChangeReceived;}
